name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
    ## REPLACE
  ## Update your dependencies to use `flutter_web`
  #flutter:
  #  sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  flutter_web: any
 # http: ^0.11.3

dev_dependencies:
  ## REPLACE
  ## Same goes for test packages
  #flutter_test:
  #  sdk: flutter

## ADD
## Add these dependencies to enable the Dart web build system
build_runner: ^1.4.0
build_web_compilers: ^2.0.0

test: ^1.3.4

#flutter:
 # uses-material-design: true
 ## fonts:
    #- family: Raleway
      #fonts:
        #- asset: assets/Raleway-Black.ttf
          #weight: 100
#    - family: Quicksand
     # fonts:
    #    - asset: assets/Quicksand-SemiBold.ttf
   #       weight: 200
  #assets:
#    - assets/
## ADD
## flutter_web packages are not published to pub.dartlang.org
## These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_clock_helper:
    path: ../flutter_clock_helper